### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by tonymullen** [ritsrivastava01/ngxFlip#1]
Running Angular CLI: 6.0.8, Node: 10.0.0, Angular: 6.0.7., Rxjs: 6.2.1.

Installing ngxFlip according to the directions in the readme my app fails to compile with the following errors:

ERROR in ./node_modules/ngx-Flip/node_modules/@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '/Users/tmullen/Dropbox/WebDev/MEAN/blackjack_test/blackjack/node_modules/ngx-Flip/node_modules/@angular/core/@angular'
ERROR in ./node_modules/ngx-Flip/node_modules/@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/Subject' in '/Users/tmullen/Dropbox/WebDev/MEAN/blackjack_test/blackjack/node_modules/ngx-Flip/node_modules/@angular/core/@angular'
ERROR in ./node_modules/ngx-Flip/node_modules/@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/merge' in '/Users/tmullen/Dropbox/WebDev/MEAN/blackjack_test/blackjack/node_modules/ngx-Flip/node_modules/@angular/core/@angular'
ERROR in ./node_modules/ngx-Flip/node_modules/@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/operator/share' in '/Users/tmullen/Dropbox/WebDev/MEAN/blackjack_test/blackjack/node_modules/ngx-Flip/node_modules/@angular/core/@angular'

**Comment by ritsrivastava01** [comment]
Fixed by @tonymullen

**Comment by natmash** [comment]
When is this going to be published to npm?

**Comment by ritsrivastava01** [comment]
@natmash Thanks for reminding, Ill move it on npm by this weekend.

**Comment by natmash** [comment]
Any update on this?

**Comment by davidhunt135** [comment]
I have the same problem, was the change pushed to npm?

**Comment by ritsrivastava01** [comment]
I' doing now will inform you guys when it's done

**Comment by ritsrivastava01** [comment]
Hi Guys its fix now pls continue to use it.

:+1:  pls star it if you feel its good

**Comment by jek-bao-choo** [comment]
It's good. Thanks.
