### ISSUE TITLE
ViewChild flipContainer is undefined at component initialization (Angular 9)

### ISSUE THREAD

**Issue by AlleXyS90** [ritsrivastava01/ngxFlip#13]
<img width="389" alt="Screenshot_7" src="https://user-images.githubusercontent.com/29358335/71906430-bb804580-3172-11ea-99e7-67a7307aa767.png">

Even if the object is initialized before page rendering, this error will be displayed in console and images will not flip at first interaction (only from second).

This happened after upgrade Angular app to v9.

How I see, the problem is for rotate() function from flip.component.ts [https://github.com/ritsrivastava01/ngxFlip/blob/master/projects/ngxflip/src/lib/flip.component.ts](url)

```
"@angular/cdk": "^9.0.0-rc.6",
"@angular/core": "~9.0.0-rc.7",
"ngx-flip": "^7.1.0",
```

target es5

**Comment by ritsrivastava01** [comment]
Hi @AlleXyS90 ,

Thanks for using this component.
I didn't update my component with A9 so I can't comment on that, however, it will greate if you create a stackblitz project and share with me so I can chek when I have time?

Ritz,

**Comment by AlleXyS90** [comment]
Hope I'll have time to do this. I checked a little, angular 9 install tslib v1.10.0, while ngx-flip have as dependency tslib@1.6.1 (can be one of posibilities)

**Comment by AlleXyS90** [comment]
A stackblitz project which get the error: [https://stackblitz.com/edit/angular-ehcxoc](url)

for me, v8.2.14 is the latest angular version which run correctly.

**Comment by ritsrivastava01** [comment]
Oh, then I need to update my application to V9. :) will do soon 
Thanks

**Comment by dirkbolte** [comment]
Just updated my application to angular 9 and I run in the same issue. Interestingly, I have 4 flip cards on my screen - the first one is rendered correctly while the others aren't. Every time I flip the first card manually, one of the others gets flipped.

**Comment by dirkbolte** [comment]
in case anyone needs a patch to apply with [patch-package](https://www.npmjs.com/package/patch-package): https://gist.github.com/dirkbolte/162c274b064779f0a55e215488223f9a

**Comment by ritsrivastava01** [comment]
Hi @dirkbolte ,

Thanks man, its working fine n I'm going to merge it then publish the new version on npm.
