### ISSUE TITLE
Multicard Flip in *ngFor loop.

### ISSUE THREAD

**Issue by Saqib92** [ritsrivastava01/ngxFlip#15]
its basically a Feature Request. 
Multiple cards to flip with *ngFor loop with auto animate.

**Comment by ritsrivastava01** [comment]
Hi,
can you pls give more details and it would be nice if you share an example?

**Comment by Saqib92** [comment]
Currently we can flip a single card in front and backwards.
My Requirement is: User can have more then 2 cards.
Reference: [Jquery Flipbox](https://krebszattila.github.io/jquery-flipbox/)

**Comment by ritsrivastava01** [comment]
Hi @Saqib92 ,
My apologies for the late reply. But you can achieve it by the loop as well.

**Comment by Saqib92** [comment]
currently it creates multiple boxes. i want just 1 box with multiple flip sides.

**Comment by ritsrivastava01** [comment]
yup sure maybe we can add that as a feature in future.

**Comment by Saqib92** [comment]
That would be great.
