### ISSUE TITLE
Mismatch between NPM module naming and package.json naming breaking AOT in Angular

### ISSUE THREAD

**Issue by Sturgelose** [ritsrivastava01/ngxFlip#3]
First of all, thanks for the module :) I had a custom made library doing the same, but this one is better tested and less glitchy than mine, so I'm swapping mine by yours!

Anyways, I've been trying to add it in my project and it works flawless. However, when building i production mode with AOT enabled, the build crashes.

The reason seems to be that this module is not AOT ready and it only works in JIT mode. I've been doing a bit of research and it seems it only changing some build configuration:
https://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/ (check AOT section).

At the moment I'm using this module for development, but I'd be willing (when I get/if I can get some time) to help to do this change in the build!

**Comment by ritsrivastava01** [comment]
Nice to hear that everything is working good, it's also thankful thought that you want to improve this lib.
Thanks in advance for your efforts and finding.
By this way we can improve this lib day by day.
Thanks a lot.
--Ritz

**Comment by Sturgelose** [comment]
Hi @ritsrivastava01 ,
Small updates (note down that I'm a bit confused).
I tried cloning your library and compiling it localy. It builds fine though reported version is 6.0.0 and package name is `@ritsrivastava/ngxflip` instead of ngx-flip. It should be ok and still work fine.

I tried installing it from my local build (done in previous step) (`npm install ../ngxFlip/dist/ngxflip/ritsrivastava-ngxflip-6.0.0.tgz`), tried building my project (changed the library to be loaded from the new package name) in prod mode and.... voila! Works perfect with AOT enabled.

I tried again uninstalling locally made version and using the online one, and I get again the same error. 
I think (and it's my best guess), that there is something wrong with the naming inside of the library. if you check the error I get (you can reproduce just creating an empty project and using the library that is server from NPM) you read the following:
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngxflip' in '/Users/sturgelose/git/frontend/apps/dash/src/app'
ERROR in /Users/sturgelose/git/frontend/libs/cards/src/lib/card/card.component.ngfactory.js
Module not found: Error: Can't resolve 'ngxflip' in '/Users/sturgelose/git/frontend/libs/cards/src/lib/card'
ERROR in /Users/sturgelose/git/frontend/node_modules/ngx-flip/ngxflip.ngfactory.js
Module not found: Error: Can't resolve 'ngxflip' in '/Users/sturgelose/git/frontend/node_modules/ngx-flip'
```

It seems it's trying to resolve `ngxflip` when the package name is `ngx-flip` (with the dash). May this be a small missconfiguration in the namings inside the package?
Mostly because the package name has the dash and all the files inside of it are missing it (maybe some magic from the compiler, though...)

So in sum, it isn't an issue with AOT precompiling, it's more with a naming issue somewhere that when using the --prod option and runs AOT it fails. I tried to attach the tgz build I created myself just so you can check, but seems this format is not allowed here....

Any ideas what could happen? Thanks again!

**Comment by ritsrivastava01** [comment]
Thanks, @Sturgelose,
I'll try to create a sample project with online lib and then try to build--prod.
let see how I can resolve it. :)

**Comment by nuwang91** [comment]
I am also facing the same issue on prod build. It seems to be a mismatch in the naming that causes the error.

**Comment by ritsrivastava01** [comment]
Dear @Sturgelose and @nuwang91,

Thanks for your input, I got some time this weekend to work on this issue and I changed the package name (previously it was '@ritsrivastava01/ngx-flip', now it's only 'ngx-flip').

Pls let me know if it working for you OR not.

Hope its working for you.
--Ritz

**Comment by Sturgelose** [comment]
@ritsrivastava01 I can confirm it's fixed :) 👍 Thanks a lot!
