### ISSUE TITLE
Question: Image covers up text. How to clearfix?

### ISSUE THREAD

**Issue by jek-bao-choo** [ritsrivastava01/ngxFlip#7]
Seeing the below code snippet.
The image will cover or overlay the word "bar". However, when it's showing the back of the card, both words "foo" and "bar" can be seen.

```
<div class="row">
  <div class="col-12">
    <div class="text-center">
      <ngx-flip [flip]="flipDiv" (click)="onClick()">
        <div front>
          <img src="https://i.imgur.com/XsbqCXt.png" class="img-fluid img-thumbnail">
        </div>
        <div back>
          <p>foo</p>
        </div>
      </ngx-flip>
    </div>
    <p>bar</p>
  </div>
</div>
```

A simplified version of the problem would be
```
<ngx-flip [flip]="flipDiv" (click)="onClick()">
   <div front><img src="https://i.imgur.com/XsbqCXt.png"></div>
   <div back>Back</div>
 </ngx-flip>
Hello World
```

Similarly the image would overlay or cover up "Hello World". However, when we flip it, we see both "Back" and "Hello World".

May I know how to solve this bug/problem? We should see the word "Bar" and "Hello World" even without flipping the card.

**Comment by jek-bao-choo** [comment]
@ritsrivastava01  Hi Rits need your help for this question. 

I found some materials that you might find useful. https://stackoverflow.com/questions/42176735/how-to-implement-a-flip-effect-using-anuglar-2-animations
https://stackblitz.com/edit/angular-card-flip

**Comment by ritsrivastava01** [comment]
@choopage can u pls share the working issue OR repo. However what I understand with your problem(2nd Example) "Hello Word" is outside the Flip component so that should not cover OR manage by flip component and if it is you can wrap the flip component in div and provide the css on that.
Hope it can help you something.
Ritz

**Comment by jek-bao-choo** [comment]
hi @ritsrivastava01 

Thanks for your reply. Didn't seem to work well by providing CSS to fix the problem.
See this repo.
https://stackblitz.com/edit/angular-nf3prb

---

Update #1: I want to achieve this outcome https://stackblitz.com/edit/angular-card-flip-3q6xng with your component library ngx-flip. Where it is responsive to screen size.

**Comment by ritsrivastava01** [comment]
@choopage this is CSS issue, you didn't give the height and width of **ngx-flip** component.
Pls, look at the working example.
https://stackblitz.com/edit/angular-scss-demo-t2mskg

**Comment by jek-bao-choo** [comment]
Noted. Thanks.

**Comment by ritsrivastava01** [comment]
:+1:  Welcome.. going to close it :)
