### ISSUE TITLE
IE Text Reversed

### ISSUE THREAD

**Issue by DrakeAnglin** [ritsrivastava01/ngxFlip#8]
In IE 11, when you flip the card, the text is reversed and it does not show the back side of the card.

**Comment by ritsrivastava01** [comment]
@DrakeAnglin  can u pls share the example on  https://stackblitz.com/

**Comment by DrakeAnglin** [comment]
I toke the exact same sample from here and put it in Stack Blitz. 

![image](https://user-images.githubusercontent.com/37958526/55742228-30182f00-59fd-11e9-9481-8046dcb7d931.png)


https://stackblitz.com/edit/angular-yyspqs
